name: "Feature Request"
description: Suggest a feature for this project
title: "[Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: | 
        Thanks for taking the time to fill out this feature request form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the problem is.
      value: "I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: ideal-solution
    attributes:
      label: Describe the solution you would like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Describe alternatives you have considered.
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: true
  - type: dropdown
    id: cv-type
    attributes:
      label: Which type of our computer vision pipelines are you using?
      multiple: true
      options:
        - Object detection for image cropping
        - Object detection for image tagging
        - Classification for image tagging
  - type: dropdown
    id: cv-task
    attributes:
      label: Which specific task from our computer vision pipelines are you using?
      multiple: true
      options:
        - Aves
        - Chiroptera
        - Lepidoptera
        - Multitaxa
        - Plant pollinator
        - Insect life stages
        - Human present
        - Flower fruit
        - Image type
        - Image ratings
  - type: textarea
    id: filename
    attributes:
      label: Filename
      description: What is the filename of the script that you would like to see improved?
      placeholder: Type your filename here
      value: "Ex. classify_images.ipynb"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of Tensorflow are you running?
      placeholder: Tensorflow version prints out at the end of Installs & Imports code blocks at the beginning of each notebook.
      value: "Ex. Version 2.8"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Any log output or other content that may be useful for developing the requested feature.
      description: Add any other context or screenshots about the feature request here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/aubricot/computer_vision_with_eol_images/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
