name: "Bug Report"
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: | 
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: cv-type
    attributes:
      label: Which type of our computer vision pipelines were you using?
      multiple: true
      options:
        - Object detection for image cropping
        - Object detection for image tagging
        - Classification for image tagging
  - type: dropdown
    id: cv-task
    attributes:
      label: Which specific task from our computer vision pipelines were you using?
      multiple: true
      options:
        - Aves
        - Chiroptera
        - Lepidoptera
        - Multitaxa
        - Plant pollinator
        - Insect life stages
        - Human present
        - Flower fruit
        - Image type
        - Image ratings
  - type: textarea
    id: filename
    attributes:
      label: filename
      description: What is the filename of the script that is giving you trouble?
      placeholder: Type your filename here
      value: "Ex. classify_images.ipynb"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of Tensorflow are you running?
      placeholder: Tensorflow version prints out at the end of Installs & Imports code blocks at the beginning of each notebook.
      value: "Ex. Version 2.8"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/aubricot/computer_vision_with_eol_images/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
